### PR TITLE
issue-205: loading site and dependencies clientlib in correct order

### LINKED ISSUE #205: Back button in hamburger on desktop has wrong hover style
The back button is missing the following styles on hover
```css
{
color: white;
cursor: pointer;
}
```
image

### PR DESCRIPTION
**Pull request by vdua**
- also adding cursor:pointer to links

Fix #205
Test URLs:
- Before: https://main--nedbank--hlxsites.hlx.live/
- After: https://issue_205--nedbank--hlxsites.hlx.live/

### CODE REVIEW

File: blocks/header/nav-utils.js [hunk 1]
```diff
@@ -12,9 +12,9 @@ const REPLACE_SCRIPTS = new Map([
 
 function appendStyles() {
   [
+    '/blocks/header/nb-clientlibs/styles/clientlibs-dependencies.css',
     '/blocks/header/nb-clientlibs/styles/clientlibs-base.css',
     '/blocks/header/nb-clientlibs/styles/clientlibs-site.css',
-    '/blocks/header/nb-clientlibs/styles/clientlibs-dependencies.css',
```
Comment (vdua) [inline blocks/header/nav-utils.js:17]: this is as done as per nedbank's site
image

**Review by sdmcraft — APPROVED** [review]
